<?php

use Illuminate\Database\Seeder;

class KegiatanEplanningTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('kegiatan_eplanning')->delete();
        
        \DB::table('kegiatan_eplanning')->insert(array (
            0 => 
            array (
                'id' => 4,
                'rkp_id' => NULL,
                'desa_id' => 2,
                'bidang_id' => 0,
                'sub_bidang_id' => NULL,
                'wilayah_id' => NULL,
                'nama_kegiatan' => 'HIV/AIDS',
                'lokasi' => 'Jl Majapahit',
                'volume' => '12',
                'manfaat' => '',
                'start_date' => '0000-00-00',
                'estimated_time' => NULL,
                'attachment' => NULL,
                'swakelola' => NULL,
                'kerjasama_antardesa' => NULL,
                'kerjasama_pihak_ketiga' => NULL,
                'jumlah' => 0,
                'sumber_biaya' => NULL,
                'rencana_pelaksana_kegiatan' => NULL,
                'status' => 'USULAN DUSUN',
                'created_at' => '2020-03-15 23:10:02',
                'updated_at' => '2020-03-15 23:10:02',
                'usulan_dusun_id' => 1,
                'satuan' => '12',
                'penerima_lk' => 21,
                'penerima_pr' => 20,
                'penerima_artm' => 20,
            ),
            1 => 
            array (
                'id' => 12,
                'rkp_id' => NULL,
                'desa_id' => 2,
                'bidang_id' => 0,
                'sub_bidang_id' => 9,
                'wilayah_id' => 13,
                'nama_kegiatan' => 'Sosialisasi penanaman padi',
                'lokasi' => NULL,
                'volume' => '45 Orang',
                'manfaat' => 'masyarakat',
                'start_date' => '0000-00-00',
                'estimated_time' => '1 hari',
                'attachment' => NULL,
                'swakelola' => NULL,
                'kerjasama_antardesa' => NULL,
                'kerjasama_pihak_ketiga' => NULL,
                'jumlah' => 7,
                'sumber_biaya' => NULL,
                'rencana_pelaksana_kegiatan' => NULL,
                'status' => 'USULAN DESA',
                'created_at' => '2020-03-21 22:38:53',
                'updated_at' => '2020-04-03 21:13:16',
                'usulan_dusun_id' => NULL,
                'satuan' => NULL,
                'penerima_lk' => NULL,
                'penerima_pr' => NULL,
                'penerima_artm' => NULL,
            ),
            2 => 
            array (
                'id' => 27,
                'rkp_id' => 6,
                'desa_id' => 2,
                'bidang_id' => 0,
                'sub_bidang_id' => 10,
                'wilayah_id' => 12,
                'nama_kegiatan' => 'HIV/AIDS2',
                'lokasi' => NULL,
                'volume' => '12',
                'manfaat' => 'masyarakat',
                'start_date' => '0000-00-00',
                'estimated_time' => '3 hari',
                'attachment' => 'https://s3-ap-southeast-1.amazonaws.com/smartdesa/attachment/I0OgvNcalmHgRnYHKc9I77mSYRXRv5zwjWbe8dca.pdf',
                'swakelola' => 'ya',
                'kerjasama_antardesa' => 'tidak',
                'kerjasama_pihak_ketiga' => 'tidak',
                'jumlah' => 30000,
                'sumber_biaya' => '1',
                'rencana_pelaksana_kegiatan' => 'KAUR TATAUSAHA',
                'status' => 'RKP',
                'created_at' => '2020-04-03 20:52:10',
                'updated_at' => '2020-04-03 20:52:10',
                'usulan_dusun_id' => NULL,
                'satuan' => NULL,
                'penerima_lk' => NULL,
                'penerima_pr' => NULL,
                'penerima_artm' => NULL,
            ),
            3 => 
            array (
                'id' => 28,
                'rkp_id' => 4,
                'desa_id' => 2,
                'bidang_id' => 0,
                'sub_bidang_id' => 9,
                'wilayah_id' => 14,
                'nama_kegiatan' => 'Bersih Lingkungan',
                'lokasi' => NULL,
                'volume' => '12 Orang',
                'manfaat' => 'masyarakat',
                'start_date' => '0000-00-00',
                'estimated_time' => '2 hari',
                'attachment' => 'https://s3-ap-southeast-1.amazonaws.com/smartdesa/attachment/1dGGOPfi7h80z0jYFO7coRn5HqE1YBZo4kBVsvBf.pdf',
                'swakelola' => 'ya',
                'kerjasama_antardesa' => 'tidak',
                'kerjasama_pihak_ketiga' => 'tidak',
                'jumlah' => 20000,
                'sumber_biaya' => '1',
                'rencana_pelaksana_kegiatan' => 'tes',
                'status' => 'RKP',
                'created_at' => '2020-04-03 21:21:11',
                'updated_at' => '2020-04-03 21:21:11',
                'usulan_dusun_id' => NULL,
                'satuan' => NULL,
                'penerima_lk' => NULL,
                'penerima_pr' => NULL,
                'penerima_artm' => NULL,
            ),
            4 => 
            array (
                'id' => 29,
                'rkp_id' => 4,
                'desa_id' => 2,
                'bidang_id' => 0,
                'sub_bidang_id' => 9,
                'wilayah_id' => 13,
                'nama_kegiatan' => 'Sosialisasi penanaman padi',
                'lokasi' => NULL,
                'volume' => '45 Orang',
                'manfaat' => 'masyarakat',
                'start_date' => '0000-00-00',
                'estimated_time' => '1 hari',
                'attachment' => 'https://s3-ap-southeast-1.amazonaws.com/smartdesa/attachment/B8g1LHPgUcBNuhab5z6g9mdh7cFnlY4LzK7ac3jS.pdf',
                'swakelola' => 'ya',
                'kerjasama_antardesa' => 'tidak',
                'kerjasama_pihak_ketiga' => 'tidak',
                'jumlah' => 7,
                'sumber_biaya' => '2',
                'rencana_pelaksana_kegiatan' => 'tes',
                'status' => 'RKP',
                'created_at' => '2020-04-03 21:21:11',
                'updated_at' => '2020-04-03 21:21:11',
                'usulan_dusun_id' => NULL,
                'satuan' => NULL,
                'penerima_lk' => NULL,
                'penerima_pr' => NULL,
                'penerima_artm' => NULL,
            ),
            5 => 
            array (
                'id' => 30,
                'rkp_id' => 4,
                'desa_id' => 2,
                'bidang_id' => 0,
                'sub_bidang_id' => 10,
                'wilayah_id' => 12,
                'nama_kegiatan' => 'HIV/AIDS2',
                'lokasi' => NULL,
                'volume' => '12 Paket',
                'manfaat' => 'masyarakat',
                'start_date' => '0000-00-00',
                'estimated_time' => '5 hari',
                'attachment' => 'https://s3-ap-southeast-1.amazonaws.com/smartdesa/attachment/cCa6r9aHDpCRdPlX4gYXDnGfXdyjxiGSXvxdwaS2.docx',
                'swakelola' => 'ya',
                'kerjasama_antardesa' => 'tidak',
                'kerjasama_pihak_ketiga' => 'tidak',
                'jumlah' => 30000,
                'sumber_biaya' => '1',
                'rencana_pelaksana_kegiatan' => 'tess',
                'status' => 'RKP',
                'created_at' => '2020-04-03 21:21:11',
                'updated_at' => '2020-04-03 21:21:11',
                'usulan_dusun_id' => NULL,
                'satuan' => NULL,
                'penerima_lk' => NULL,
                'penerima_pr' => NULL,
                'penerima_artm' => NULL,
            ),
            6 => 
            array (
                'id' => 31,
                'rkp_id' => 4,
                'desa_id' => 2,
                'bidang_id' => 0,
                'sub_bidang_id' => 10,
                'wilayah_id' => 11,
                'nama_kegiatan' => 'Rehab kantor desa',
                'lokasi' => NULL,
                'volume' => '12 Paket',
                'manfaat' => 'masyarakat',
                'start_date' => '0000-00-00',
                'estimated_time' => '4 hari',
                'attachment' => 'https://s3-ap-southeast-1.amazonaws.com/smartdesa/attachment/sCjUeA3SSX15rGI7zGkzqV9ojHmAXPphFwh0UFQD.docx',
                'swakelola' => 'tidak',
                'kerjasama_antardesa' => 'ya',
                'kerjasama_pihak_ketiga' => 'tidak',
                'jumlah' => 3000000,
                'sumber_biaya' => '1',
                'rencana_pelaksana_kegiatan' => 'tess',
                'status' => 'RKP',
                'created_at' => '2020-04-03 21:21:11',
                'updated_at' => '2020-04-03 21:21:11',
                'usulan_dusun_id' => NULL,
                'satuan' => NULL,
                'penerima_lk' => NULL,
                'penerima_pr' => NULL,
                'penerima_artm' => NULL,
            ),
            7 => 
            array (
                'id' => 32,
                'rkp_id' => 4,
                'desa_id' => 2,
                'bidang_id' => 0,
                'sub_bidang_id' => 9,
                'wilayah_id' => 13,
                'nama_kegiatan' => 'Sosialisasi penanaman padi',
                'lokasi' => NULL,
                'volume' => '45 Orang',
                'manfaat' => 'masyarakat',
                'start_date' => '0000-00-00',
                'estimated_time' => '1 hari',
                'attachment' => 'https://s3-ap-southeast-1.amazonaws.com/smartdesa/attachment/uB6nUh2VBfTP4MGLo3QnZGreaSr3d6vkOhv7okHr.pdf',
                'swakelola' => 'tidak',
                'kerjasama_antardesa' => 'ya',
                'kerjasama_pihak_ketiga' => 'tidak',
                'jumlah' => 7,
                'sumber_biaya' => '2',
                'rencana_pelaksana_kegiatan' => NULL,
                'status' => 'RKP',
                'created_at' => '2020-04-03 21:21:11',
                'updated_at' => '2020-04-03 21:21:11',
                'usulan_dusun_id' => NULL,
                'satuan' => NULL,
                'penerima_lk' => NULL,
                'penerima_pr' => NULL,
                'penerima_artm' => NULL,
            ),
        ));
        
        
    }
}