<?php

use Illuminate\Database\Seeder;

class PendudukTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {


        \DB::table('penduduk')->delete();

        \DB::table('penduduk')->insert(array(
            0 =>
            array(
                'id' => 13,
                'desa_id' => 2,
                'nama' => 'Wayan Bayu',
                'nik' => '510205290819930004',
                'id_kk' => 0,
                'kk_level' => 1,
                'id_rtm' => 0,
                'rtm_level' => 0,
                'sex' => 1,
                'tempatlahir' => 'DENPASAR',
                'tanggallahir' => '1993-08-29',
                'agama_id' => 2,
                'pendidikan_kk_id' => 8,
                'pendidikan_sedang_id' => 12,
                'pekerjaan_id' => 15,
                'status_kawin_id' => 1,
                'warganegara_id' => 1,
                'dokumen_paspor' => NULL,
                'dokumen_kitas' => NULL,
                'ayah_nik' => '510205290819660002',
                'ibu_nik' => '510205290819410007',
                'nama_ayah' => 'Ketut Durya',
                'nama_ibu' => 'Kadek Nia',
                'foto' => '',
                'golongan_darah_id' => 2,
                'dusun_id' => 12,
                'status' => 1,
                'alamat_sebelumnya' => 'Jl Wanasari no 1',
                'alamat_sekarang' => 'Jl Wanasari no 1',
                'status_dasar' => 1,
                'hamil' => 0,
                'cacat_id' => 7,
                'sakit_menahun_id' => 14,
                'akta_lahir' => '2044/K/1993',
                'akta_perkawinan' => NULL,
                'tanggalperkawinan' => NULL,
                'akta_perceraian' => NULL,
                'tanggalperceraian' => NULL,
                'cara_kb_id' => 99,
                'telepon' => '081933748312',
                'tanggal_akhir_paspor' => NULL,
                'no_kk_sebelumnya' => '510205290820160002',
                'ktp_el' => 0,
                'status_rekam_id' => 3,
                'waktu_lahir' => '11:00',
                'tempat_dilahirkan_id' => 1,
                'jenis_kelahiran_id' => 1,
                'kelahiran_anak_ke' => 1,
                'penolong_kelahiran_id' => 1,
                'berat_lahir' => '1',
                'panjang_lahir' => '89',
                'token' => 'ebf90a21790430a965760e86e850faa0ae7344df51f450fe44a83cc3dac7ca0a',
                'created_at' => '2018-09-02 21:29:34',
                'updated_at' => '2018-09-02 21:29:34',
            ),
            1 =>
            array(
                'id' => 14,
                'desa_id' => 2,
                'nama' => 'Ketut Jina',
                'nik' => '510203101019980004',
                'id_kk' => 0,
                'kk_level' => 4,
                'id_rtm' => 0,
                'rtm_level' => 0,
                'sex' => 2,
                'tempatlahir' => 'DENPASAR',
                'tanggallahir' => '1998-10-10',
                'agama_id' => 5,
                'pendidikan_kk_id' => 5,
                'pendidikan_sedang_id' => 11,
                'pekerjaan_id' => 3,
                'status_kawin_id' => 1,
                'warganegara_id' => 1,
                'dokumen_paspor' => NULL,
                'dokumen_kitas' => NULL,
                'ayah_nik' => '510203101019660002',
                'ibu_nik' => '510203101019660004',
                'nama_ayah' => 'Ketut Durya',
                'nama_ibu' => 'Kadek Nia',
                'foto' => '',
                'golongan_darah_id' => 4,
                'dusun_id' => 12,
                'status' => 1,
                'alamat_sebelumnya' => 'Jl Lumintang 3',
                'alamat_sekarang' => 'Jl Lumintang 3',
                'status_dasar' => 1,
                'hamil' => 0,
                'cacat_id' => 7,
                'sakit_menahun_id' => 14,
                'akta_lahir' => '2011/KT/1998',
                'akta_perkawinan' => NULL,
                'tanggalperkawinan' => NULL,
                'akta_perceraian' => NULL,
                'tanggalperceraian' => NULL,
                'cara_kb_id' => 99,
                'telepon' => '0813665512312',
                'tanggal_akhir_paspor' => NULL,
                'no_kk_sebelumnya' => '510203101020010002',
                'ktp_el' => 2,
                'status_rekam_id' => 2,
                'waktu_lahir' => '10:00',
                'tempat_dilahirkan_id' => 2,
                'jenis_kelahiran_id' => 1,
                'kelahiran_anak_ke' => 2,
                'penolong_kelahiran_id' => 2,
                'berat_lahir' => '1',
                'panjang_lahir' => '80',
                'token' => 'ebf90a21790430a965760e86e850faa0ae7344df51f450fe44a83cc3dac7ca0b',
                'created_at' => '2018-09-02 21:35:10',
                'updated_at' => '2018-09-02 21:35:10',
            ),
            2 =>
            array(
                'id' => 15,
                'desa_id' => 2,
                'nama' => 'Alex II',
                'nik' => '510203101019980006',
                'id_kk' => 0,
                'kk_level' => 5,
                'id_rtm' => 0,
                'rtm_level' => 0,
                'sex' => 2,
                'tempatlahir' => 'DENPASAR',
                'tanggallahir' => '1998-10-10',
                'agama_id' => 5,
                'pendidikan_kk_id' => 5,
                'pendidikan_sedang_id' => 11,
                'pekerjaan_id' => 3,
                'status_kawin_id' => 1,
                'warganegara_id' => 1,
                'dokumen_paspor' => NULL,
                'dokumen_kitas' => NULL,
                'ayah_nik' => '510203101019660001',
                'ibu_nik' => '510203101019660004',
                'nama_ayah' => 'Ketut Supana',
                'nama_ibu' => 'Putu Julia',
                'foto' => '',
                'golongan_darah_id' => 4,
                'dusun_id' => 12,
                'status' => 1,
                'alamat_sebelumnya' => 'Jl Lumintang 3',
                'alamat_sekarang' => 'Jl Lumintang 3',
                'status_dasar' => 1,
                'hamil' => 0,
                'cacat_id' => 7,
                'sakit_menahun_id' => 14,
                'akta_lahir' => '2011/KT/1998',
                'akta_perkawinan' => NULL,
                'tanggalperkawinan' => NULL,
                'akta_perceraian' => NULL,
                'tanggalperceraian' => NULL,
                'cara_kb_id' => 99,
                'telepon' => '0813665512312',
                'tanggal_akhir_paspor' => NULL,
                'no_kk_sebelumnya' => '510203101020010002',
                'ktp_el' => 2,
                'status_rekam_id' => 2,
                'waktu_lahir' => '10:00',
                'tempat_dilahirkan_id' => 2,
                'jenis_kelahiran_id' => 1,
                'kelahiran_anak_ke' => 2,
                'penolong_kelahiran_id' => 2,
                'berat_lahir' => '1',
                'panjang_lahir' => '80',
                'token' => 'ebf90a21790430a965760e86e850faa0ae7344df51f450fe44a83cc3dac7ca0c',
                'created_at' => '2018-09-02 21:35:10',
                'updated_at' => '2018-09-02 21:35:10',
            ),
        ));
    }
}
